export default [
    {
        id: 1,
        title: "Mount Fuji",
        location: "FUJI, JAPAN",
        googleMapsUrl: "https://goo.gl/maps/1DGM5WrWnATgkSNB8",
        startDate: "12 Jan, 2021",
        endDate: "24 Jan, 2021",
        description: "Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists.",
        imageUrl: "https://source.unsplash.com/V7X-N7msDoc",
        imageLocation: "luke-stackpoole-V7X-N7msDoc-unsplash.jpg",
    },
    {
        id: 2,
        title: "Sydney Opera House",
        location: "SYDNEY, AUSTRALIA",
        googleMapsUrl: "https://goo.gl/maps/en9osV5TG7EWLxwM7",
        startDate: "27 May, 2021",
        endDate: "8 Jun, 2021",
        description: "The Sydney Opera House is a multi-venue performing arts centre in Sydney. Located on the banks of the Sydney Harbour, it is often regarded as one of the 20th century's most famous and distinctive buildings.",
        imageUrl: "https://source.unsplash.com/K1bi_VBZHng",
        imageLocation: "andreas-dress-K1bi_VBZHng-unsplash.jpg",
    },
    {
        id: 3,
        title: "Geiranger Fjord",
        location: "SUNNMØRE, NORWAY",
        googleMapsUrl: "https://goo.gl/maps/R2Mpfd7BeTc245m97",
        startDate: "1 Oct, 2021",
        endDate: "18 Nov, 2021",
        description: "The Geiranger Fjord is a fjord in the Sunn2møre region of Møre og Romsdal county, Norway. It is located entirely in the Stranda Municipality.",
        imageUrl: "https://source.unsplash.com/jgAaX0zkYCI",
        imageLocation: "alexander-sinn-jgAaX0zkYCI-unsplash.jpg",
    },
    {
        id: 4,
        title: "The Ganges",
        location: "HARIDWAR, UTTARAKHAND",
        googleMapsUrl: "https://goo.gl/maps/ZfKvhmmuHA8St6Eu6",
        startDate: "July, 2002",
        endDate: "2003",
        description: "Haridwar is an ancient city and important Hindu pilgrimage site in North India's Uttarakhand state, where the River Ganges exits the Himalayan foothills.",
        imageUrl: "https://source.unsplash.com/aW6rNqhQzi4",
        imageLocation: "saurabh-mishra-aW6rNqhQzi4-unsplash.jpg",
    },
    {
        id: 5,
        title: "Dwaraka  Temple",
        location: "DWARAKA, GUJARAT",
        googleMapsUrl: "https://goo.gl/maps/jJSZ1nytFQjizD2cA",
        startDate: "2007",
        endDate: "2008",
        description: "Dwarka is an ancient city in the northwestern Indian state of Gujarat. It’s known as a Hindu pilgrimage site. The ancient Dwarkadhish Temple has an elaborately tiered main shrine, a carved entrance and a black-marble idol of Lord Krishna.",
        imageUrl: "https://source.unsplash.com/NQp0CsUZPpk",
        imageLocation: "pandav-tank-NQp0CsUZPpk-unsplash.jpg",
    },
    {
        id: 6,
        title: "Kashmir Valley",
        location: "SRINAGAR, JAMMU & KASHMIR",
        googleMapsUrl: "https://goo.gl/maps/dseLfxPJsuaNqXy67",
        startDate: "15 August, 2012",
        endDate: "September, 2012",
        description: "The Kashmir Valley, also known as the Vale of Kashmir, is an intermontane valley concentrated in Jammu and Kashmir. The valley is bounded on the southwest by the Pir Panjal Range and on the northeast by the main Himalayas range.",
        imageUrl: "https://source.unsplash.com/4B61rSnCLj0",
        imageLocation: "abdullah-tariq-4B61rSnCLj0-unsplash.jpg",
    },
    {
        id: 7,
        title: "Mount Vaishno Devi",
        location: "JAMMU, JAMMU & KASHMIR",
        googleMapsUrl: "https://goo.gl/maps/vLHHS7EdX3HhHXdb9",
        startDate: "3 September, 2014",
        endDate: "October, 2014",
        description: "The Vaishno Devi Temple is an important Hindu temple dedicated to the Goddess Durga located in Katra at the Trikuta Mountains in Jammu and Kashmir. The temple is one of the 51 holy sites dedicated to Durga in India.",
        imageUrl: "https://source.unsplash.com/xm-2kl60CwY",
        imageLocation: "narinder-pal-xm-2kl60CwY-unsplash-crop.jpg",
    },
    {
        id: 8,
        title: "Mahakal Temple",
        location: "UJJAIN, INDIA",
        googleMapsUrl: "https://goo.gl/maps/3KkBWmNvmMFiJen76",
        startDate: "2015",
        endDate: "2016",
        description: "Mahakaleshwar is a Hindu temple dedicated to Shiva and is one of the 12 holy shrines which are said to be the most sacred abodes of Shiva. It's located in the ancient city of Ujjain on the banks of holy river Shipra, in India.",
        imageUrl: "https://source.unsplash.com/cbd4QgctWPM",
        imageLocation: "ankit-dandhare-cbd4QgctWPM-unsplash-crop.jpg",
    },
    {
        id: 9,
        title: "Port of Blair",
        location: "ANDAMAN ISLANDS, INDIA",
        googleMapsUrl: "https://goo.gl/maps/6QR3knWUiSADY5pe7",
        startDate: "2015",
        endDate: "2016",
        description: "Port Blair on South Andaman Island is the capital city of Andaman & Nicobar Islands in the Bay of Bengal. Its seafront Cellular Jail, completed in 1906, hints at its past as a British penal colony and is now a memorial to Indian independence activists.",
        imageUrl: "https://source.unsplash.com/wSyuQa3n-W8",
        imageLocation: "aleksandra-zelena-wSyuQa3n-W8-unsplash.jpg",
    },
    {
        id: 10,
        title: "Patiala",
        location: "PUNJAB, INDIA",
        googleMapsUrl: "https://goo.gl/maps/HZ4sJCDKbwujB1Qg8",
        startDate: "2018",
        endDate: "2019",
        description: "Patiala is a city in Punjab, northwestern India. Patiala state was established in 1763 by Ala Singh, a Jat Sikh chieftain, who laid the foundation of the Patiala fort known as Qila Mubarak, around 'which the present city of Patiala is built.",
        imageUrl: "https://source.unsplash.com/bq9BxsOk6GI",
        imageLocation: "sahil-yadav-bq9BxsOk6GI-unsplash.jpg",
    },
]
